-- CreateTable
CREATE TABLE `approvisionement` (
    `ID_APRO` INTEGER NOT NULL AUTO_INCREMENT,
    `ID_U` INTEGER NOT NULL,
    `ID_FOR` INTEGER NOT NULL,
    `DEVIS` DECIMAL(10, 0) NULL,
    `DATE` DATE NULL,
    `ENTREPRISE` VARCHAR(255) NULL,
    `ADRESSE` VARCHAR(255) NULL,
    `TELEPHONE` BIGINT NULL,

    INDEX `FK_FAIRE`(`ID_U`),
    INDEX `FK_FOUNIR`(`ID_FOR`),
    PRIMARY KEY (`ID_APRO`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `categorie` (
    `ID_CAT` INTEGER NOT NULL AUTO_INCREMENT,
    `CAT_ID_CAT` INTEGER NULL,
    `LIBELLE` LONGTEXT NULL,
    `SUJET` TEXT NULL,

    INDEX `FK_APPARTIENT_CAT`(`CAT_ID_CAT`),
    PRIMARY KEY (`ID_CAT`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `contient` (
    `ID_APRO` INTEGER NOT NULL,
    `ID_LIVRE` BIGINT NOT NULL,
    `QTE` BIGINT NULL,

    INDEX `FK_CONTIENT`(`ID_LIVRE`),
    PRIMARY KEY (`ID_APRO`, `ID_LIVRE`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `emprunt_livre_etudiant` (
    `IDLE` BIGINT NOT NULL AUTO_INCREMENT,
    `N_INVENTAIRE` BIGINT NOT NULL,
    `N_APOGEE` INTEGER NOT NULL,
    `ID_U` INTEGER NOT NULL,
    `DATE_D` DATE NULL,
    `DATE_F` DATE NULL,
    `DATE_R` DATE NULL,
    `OBSERVATIONLE` TEXT NULL,

    INDEX `FK_EMPRUNTER_LIVRE_ETUDIANT`(`N_INVENTAIRE`),
    INDEX `FK_EMPRUNTE_LIVRE_ETUDIANT`(`N_APOGEE`),
    INDEX `FK_SIGNER_LIVRE_ETUDIANT`(`ID_U`),
    PRIMARY KEY (`IDLE`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `emprunt_livre_prof` (
    `IDLP` BIGINT NOT NULL AUTO_INCREMENT,
    `N_INVENTAIRE` BIGINT NOT NULL,
    `ID_PROF` INTEGER NOT NULL,
    `ID_U` INTEGER NOT NULL,
    `DATE_D` DATE NULL,
    `DATE_F` DATE NULL,
    `DATE_R` DATE NULL,
    `OBSERVATIONLP` TEXT NULL,

    INDEX `FK_EMPRUNTER_LIVRE_PROF`(`N_INVENTAIRE`),
    INDEX `FK_EMPRUNTE_LIVRE_PROF`(`ID_PROF`),
    INDEX `FK_SIGNER_LIVRE_PROF`(`ID_U`),
    PRIMARY KEY (`IDLP`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `emprunt_pfe_etudiant` (
    `IDPE` BIGINT NOT NULL AUTO_INCREMENT,
    `IDPFE` BIGINT NOT NULL,
    `ID_U` INTEGER NOT NULL,
    `N_APOGEE` INTEGER NOT NULL,
    `DATE_D` DATE NULL,
    `DATE_F` DATE NULL,
    `DATE_R` DATE NULL,
    `OBSERVATIONPE` TEXT NULL,

    INDEX `FK_EMPRUNTER_PFE_ETUDIANT`(`IDPFE`),
    INDEX `FK_EMPRUNTE_PFE_ETUDIANT`(`N_APOGEE`),
    INDEX `FK_SIGNER_PFE_ETUDIANT`(`ID_U`),
    PRIMARY KEY (`IDPE`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `emprunt_pfe_prof` (
    `IDPP` BIGINT NOT NULL AUTO_INCREMENT,
    `ID_U` INTEGER NOT NULL,
    `IDPFE` BIGINT NOT NULL,
    `ID_PROF` INTEGER NOT NULL,
    `DATE_D` DATE NULL,
    `DATE_F` DATE NULL,
    `DATE_R` DATE NULL,
    `OBSERVATIONPP` TEXT NULL,

    INDEX `FK_EMPRUNTER_PFE_PROF`(`IDPFE`),
    INDEX `FK_EMPRUNTE_PFE_PROF`(`ID_PROF`),
    INDEX `FK_SIGNER_PFE_PROF`(`ID_U`),
    PRIMARY KEY (`IDPP`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `etudiant` (
    `N_APOGEE` INTEGER NOT NULL,
    `NOM` CHAR(100) NULL,
    `PRENOM` CHAR(100) NULL,
    `FILERE` CHAR(20) NULL,

    PRIMARY KEY (`N_APOGEE`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `exemplaire` (
    `N_INVENTAIRE` BIGINT NOT NULL AUTO_INCREMENT,
    `ID_LIVRE` BIGINT NOT NULL,
    `OBSERVATIONE` TEXT NULL,

    INDEX `FK_AVOIR`(`ID_LIVRE`),
    PRIMARY KEY (`N_INVENTAIRE`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `fournisseur` (
    `ID_FOR` INTEGER NOT NULL AUTO_INCREMENT,
    `NOM` CHAR(100) NULL,
    `PRENOM` CHAR(100) NULL,
    `GMAIL` VARCHAR(255) NULL,
    `ADDRESSE` VARCHAR(255) NULL,
    `TELEPHONE` BIGINT NULL,

    PRIMARY KEY (`ID_FOR`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `livre` (
    `ID_LIVRE` BIGINT NOT NULL AUTO_INCREMENT,
    `TITRE` VARCHAR(255) NULL,
    `AUTHEUR` CHAR(100) NULL,
    `ID_CAT` INTEGER NOT NULL,
    `EDITEUR` VARCHAR(255) NULL,
    `DATE_EDITION` DATE NULL,
    `CODE` INTEGER NULL,
    `OBSERVATIONL` TEXT NULL,
    `PAGE_DE_GARDE` VARCHAR(255) NULL,
    `SOMAIRE` VARCHAR(255) NULL,
    `PRIX` DECIMAL(10, 0) NULL,

    INDEX `FK_APPARTIENT`(`ID_CAT`),
    PRIMARY KEY (`ID_LIVRE`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `pfe` (
    `IDPFE` BIGINT NOT NULL AUTO_INCREMENT,
    `SUJET` TEXT NULL,
    `REALISATEUR` TEXT NULL,
    `ENCADRANT` CHAR(100) NULL,
    `DATE_REALISATION` YEAR NULL,

    PRIMARY KEY (`IDPFE`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `prof` (
    `ID_PROF` INTEGER NOT NULL AUTO_INCREMENT,
    `NOM` CHAR(100) NULL,
    `PRENOM` CHAR(100) NULL,
    `DEPARTEMENT` CHAR(50) NULL,

    PRIMARY KEY (`ID_PROF`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `utilisateur` (
    `ID_U` INTEGER NOT NULL AUTO_INCREMENT,
    `NOM` CHAR(100) NULL,
    `PRENOM` CHAR(100) NULL,
    `TELEPHONE` BIGINT NULL,
    `LOGIN` VARCHAR(100) NULL,
    `PASSWORD` VARCHAR(255) NULL,

    PRIMARY KEY (`ID_U`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `approvisionement` ADD CONSTRAINT `FK_FAIRE` FOREIGN KEY (`ID_U`) REFERENCES `utilisateur`(`ID_U`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `approvisionement` ADD CONSTRAINT `FK_FOUNIR` FOREIGN KEY (`ID_FOR`) REFERENCES `fournisseur`(`ID_FOR`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `categorie` ADD CONSTRAINT `FK_APPARTIENT_CAT` FOREIGN KEY (`CAT_ID_CAT`) REFERENCES `categorie`(`ID_CAT`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `contient` ADD CONSTRAINT `FK_CONTIENT` FOREIGN KEY (`ID_LIVRE`) REFERENCES `livre`(`ID_LIVRE`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `contient` ADD CONSTRAINT `FK_CONTIENT2` FOREIGN KEY (`ID_APRO`) REFERENCES `approvisionement`(`ID_APRO`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `emprunt_livre_etudiant` ADD CONSTRAINT `FK_EMPRUNT_LIVRE_ETUDIANT2` FOREIGN KEY (`N_INVENTAIRE`) REFERENCES `exemplaire`(`N_INVENTAIRE`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `emprunt_livre_etudiant` ADD CONSTRAINT `FK_EMPRUNT_LIVRE_ETUDIANT3` FOREIGN KEY (`N_APOGEE`) REFERENCES `etudiant`(`N_APOGEE`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `emprunt_livre_etudiant` ADD CONSTRAINT `FK_EMPRUNT_LIVRE_ETUDIANT` FOREIGN KEY (`ID_U`) REFERENCES `utilisateur`(`ID_U`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `emprunt_livre_prof` ADD CONSTRAINT `FK_EMPRUNT_LIVRE_PROF3` FOREIGN KEY (`N_INVENTAIRE`) REFERENCES `exemplaire`(`N_INVENTAIRE`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `emprunt_livre_prof` ADD CONSTRAINT `FK_EMPRUNT_LIVRE_PROF2` FOREIGN KEY (`ID_PROF`) REFERENCES `prof`(`ID_PROF`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `emprunt_livre_prof` ADD CONSTRAINT `FK_EMPRUNT_LIVRE_PROF` FOREIGN KEY (`ID_U`) REFERENCES `utilisateur`(`ID_U`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `emprunt_pfe_etudiant` ADD CONSTRAINT `FK_EMPRUNT_PFE_ETUDIANT2` FOREIGN KEY (`IDPFE`) REFERENCES `pfe`(`IDPFE`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `emprunt_pfe_etudiant` ADD CONSTRAINT `FK_EMPRUNT_PFE_ETUDIANT3` FOREIGN KEY (`N_APOGEE`) REFERENCES `etudiant`(`N_APOGEE`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `emprunt_pfe_etudiant` ADD CONSTRAINT `FK_EMPRUNT_PFE_ETUDIANT` FOREIGN KEY (`ID_U`) REFERENCES `utilisateur`(`ID_U`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `emprunt_pfe_prof` ADD CONSTRAINT `FK_EMPRUNT_PFE_PROF2` FOREIGN KEY (`IDPFE`) REFERENCES `pfe`(`IDPFE`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `emprunt_pfe_prof` ADD CONSTRAINT `FK_EMPRUNT_PFE_PROF3` FOREIGN KEY (`ID_PROF`) REFERENCES `prof`(`ID_PROF`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `emprunt_pfe_prof` ADD CONSTRAINT `FK_EMPRUNT_PFE_PROF` FOREIGN KEY (`ID_U`) REFERENCES `utilisateur`(`ID_U`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `exemplaire` ADD CONSTRAINT `FK_AVOIR` FOREIGN KEY (`ID_LIVRE`) REFERENCES `livre`(`ID_LIVRE`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `livre` ADD CONSTRAINT `FK_APPARTIENT` FOREIGN KEY (`ID_CAT`) REFERENCES `categorie`(`ID_CAT`) ON DELETE RESTRICT ON UPDATE RESTRICT;
